//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebROM
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Model1Container : DbContext
    {
        public Model1Container()
            : base("name=Model1Container")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Users> UsersSet { get; set; }
        public DbSet<Rollen> RollenSet { get; set; }
        public DbSet<Zentren> ZentrenSet { get; set; }
        public DbSet<StudienÜbersicht> StudienÜbersichtSet { get; set; }
        public DbSet<StudieRollenNutzerZuteilung> StudieRollenNutzerZuteilungSet { get; set; }
    }
}
