//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebROM
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudieRollenNutzerZuteilung
    {
        public int UsersUserID { get; set; }
        public Nullable<int> RollenRollenID { get; set; }
        public Nullable<int> StudienÜbersichtStudienID { get; set; }
        public string StudienÜbersichtBeratungsnummer { get; set; }
        public Nullable<int> ZentrenZentrumsID { get; set; }
        public string ID { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual Rollen Rollen { get; set; }
        public virtual StudienÜbersicht StudienÜbersicht { get; set; }
        public virtual Zentren Zentren { get; set; }
    }
}
