//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebROM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zentren
    {
        public Zentren()
        {
            this.StudieRollenNutzerZuteilung = new HashSet<StudieRollenNutzerZuteilung>();
        }
    
        public int ZentrumsID { get; set; }
        public string Zentrumsname { get; set; }
    
        public virtual ICollection<StudieRollenNutzerZuteilung> StudieRollenNutzerZuteilung { get; set; }
    }
}
